IF
  Global("gwitness","GLOBAL",7)
  See([PC])
  Range([PC],10)
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
    SetGlobal("gwitness","GLOBAL",9)
END

IF
  Global("gwitness","GLOBAL",8)
  See([PC])
  Range([PC],10)
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
    SetGlobal("gwitness","GLOBAL",9)
END

IF
  Global("gwitness","GLOBAL",10)
THEN
  RESPONSE #100
    EscapeArea()
    SetGlobal("gwitness","GLOBAL",11)
END

