IF
  Global("DD3318","GLOBAL",0)
THEN
  RESPONSE #100
    CreateCreature("bgSH01",[657.822],4)
    CreateCreature("bgSH02",[718.603],4)
    CreateCreature("bgSH03",[945.551],4)
    CreateCreature("bgSH04",[636.418],4)
    CreateCreature("bgSH05",[359.548],4)
    CreateCreature("bgSH06",[203.665],4)
    CreateCreature("bgSH07",[486.623],4)
    SetGlobal("DD3318","GLOBAL",1)
END

IF
  Global("bgenchant","GLOBAL",3)
THEN
  RESPONSE #100
    StartCutSceneMode()
    StartCutScene("bgward")
END

